apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: onetouch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: docker.io/pankajdevops2403/backend:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysql.onetouch.svc.cluster.local
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_DATABASE
        envFrom:
          - configMapRef:
              name: app-config
