apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: onetouch
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # Exposed port inside the cluster
      targetPort: 8080  # Container port
  type: ClusterIP
