# Purpose: expose frontend inside cluster (Istio will route external traffic to it).

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: onetouch
spec:
  type: NodePort        # 🔥 change this line
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080     # optional, else auto-assign (range 30000–32767)

