# Purpose: tells ArgoCD to sync k8s-manifests folder into onetouch namespace.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devopspankaj77/three-tier-app  # edit to your repo
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: onetouch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
