apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: onetouch
data:
  APP_ENV: "dev"
  APP_DEBUG: "true"
  LOG_LEVEL: "info"
  BACKEND_URL: "http://backend.onetouch.svc.cluster.local:8080"
