apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backend
  namespace: onetouch
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend   # <- Ye tere Deployment ka naam hona chahiye
  service:
    port: 8080      # <- Service port jo Istio VirtualService me expose hoga
    targetPort: 8080 # <- (optional, agar backend container 8080 expose kar raha hai)
  analysis:
    interval: 1m       # Canary analysis har 1 minute me chalega
    threshold: 5        # Max failed checks allowed
    stepWeight: 5       # Canary traffic increment percentage
    maxWeight: 50       # Max traffic % canary ko milega
    metrics:
    - name: request-success-rate
      interval: 1m
      threshold: 99     # Min success rate required (%)
      provider:
        type: prometheus
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          (sum(rate(istio_requests_total{destination_service=~"backend.onetouch.svc.cluster.local.*",response_code!~"5.*"}[5m])) 
          /
          sum(rate(istio_requests_total{destination_service=~"backend.onetouch.svc.cluster.local.*"}[5m])))*100
    - name: request-duration
      interval: 30s
      threshold: 500     # max 500ms latency
      provider:
        type: prometheus
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(0.99,
            sum(rate(istio_request_duration_milliseconds_bucket{destination_service=~"backend.onetouch.svc.cluster.local.*"}[5m]))
            by (le))
