name: Three-Tier App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  DOCKER_HUB_USERNAME: pankajdevops2403

jobs:
  build-frontend:
    runs-on: self-hosted
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (Frontend)
        run: npm install

      - name: Set NODE_OPTIONS environment variable to bypass OpenSSL issue
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      # - name: Build frontend
      #   run: npm run build

      - name: Build Docker image (Frontend)
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }} .

      - name: Push Docker image (Frontend)
        run: |
          docker login
          docker push ${{ env.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }}

  build-backend:
    runs-on: self-hosted
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (Backend)
        run: npm install

      - name: Run tests (Backend)
        run: npm test || echo "⚠️ Tests failed, skipping..."

      - name: Build Docker image (Backend)
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }} .

      - name: Push Docker image (Backend)
        run: |
          docker login
          docker push ${{ env.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|docker.io/pankajdevops2403/backend:.*|docker.io/pankajdevops2403/backend:${{ github.sha }}|g" k8s-manifests/backend/deployment.yaml
          sed -i "s|docker.io/pankajdevops2403/frontend:.*|docker.io/pankajdevops2403/frontend:${{ github.sha }}|g" k8s-manifests/frontend/deployment.yaml
      

      - name: Commit and Push updated manifests
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s-manifests/
          git commit -m "Update image tags to ${{ github.sha }}"
          git push origin main
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/v2.11.2/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd